title = "Spearfish | Smart funding for small business | Founded by Sherrie Gossett"
baseURL = "www.spearfishcap.com"
languageCode = "en-us"
themesDir = "../.."
theme = "hugo-serif-theme"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
google_analytics_id = ""
google_tag_manager_id = ""

  [params.logo]
  standard = "images/spearfish-logo2.png"
  mobile = "images/spearfish-logo2.png"
  alt = "spearfish logo"

  [params.homepage_meta_tags]
  meta_description = "Get business financing that adds no debt to your balance sheet. Includes credit protection against customers who may go bankrupt before they pay you. "
  meta_og_title = "Spearfish: Fast funding for small business"
  meta_og_type = "website"
  meta_og_url = "https://www.spearfishcap.com"
  meta_og_image = "https://www.spearfishcap.com/images/bridge-financing-spearfish.png"
  meta_og_description = "Spearfish makes it easy for small business owners to get the funding they need -- fast."
  meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@spearfishcap"
    meta_twitter_creator = "@sherrie_go"
    meta_twitter_image = "https://www.spearfishcap.com/images/bridge-financing-spearfish.png"



[menu]
  # Main Menu
[[menu.main]]
name = "Services"
url = "/services/"
weight = 1


[[menu.footer]]
name = "Home"
url = "/"
weight = 1

[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2
