title = "Spearfish | Smart funding for small business | Founded by Sherrie Gossett"
baseURL = "www.spearfishcap.com"
languageCode = "en-us"
themesDir = "../.."
theme = "hugo-serif-theme"

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[params]
google_analytics_id = ""
google_tag_manager_id = ""

  [params.logo]
  standard = "images/spearfish-logo2.png"
  mobile = "images/spearfish-logo2.png"
  alt = "spearfish logo"

  [params.homepage_meta_tags]
  meta_description = "Get business financing that adds no debt to your balance sheet. Includes credit protection against customers who may go bankrupt before they pay you. "
  meta_og_title = "Spearfish: Fast funding for small business"
  meta_og_type = "website"
  meta_og_url = "https://www.spearfishcap.com"
  meta_og_image = "https://www.spearfishcap.com/images/bridge-financing-spearfish.png"
  meta_og_description = "Spearfish makes it easy for small business owners to get the funding they need -- fast."
  meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@spearfishcap"
    meta_twitter_creator = "@sherrie_go"
    meta_twitter_image = "https://www.spearfishcap.com/images/bridge-financing-spearfish.png"



[menu]
  # Main Menu
[[menu.main]]
name = "Services"
url = "/services/"
weight = 1


[[menu.footer]]
name = "Home"
url = "/"
weight = 1

[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2
