title = "Spearfish"
baseURL = "www.spearfishcap.com"
languageCode = "en-us"
themesDir = "../.."
theme = "hugo-serif-theme"

[params]
google_analytics_id = ""
google_tag_manager_id = ""

  [params.logo]
  standard = "images/spearfish-logo2.png"
  mobile = "images/spearfish-logo2.png"
  alt = "spearfish logo"

  [params.homepage_meta_tags]
  meta_description = "Fast funding for small business. Same day or 24-72 hour turnaround possible. Good credit, bad credit, no credit."
  meta_og_title = "Spearfish: Fast funding for small business"
  meta_og_type = "website"
  meta_og_url = "https://www.spearfishcap.com"
  meta_og_image = "/images/small-business-growth.svg"
  meta_og_description = "Spearish makes it easy for small business owners to get the funding they need -- fast."
  meta_twitter_card = "summary_large_image"
  meta_twitter_site = "@spearfishcap"
  meta_twitter_creator = "@spearfishcap"

[[menu.main]]
name = "Services"
url = "/services/"
weight = 1


[[menu.footer]]
name = "Home"
url = "/"
weight = 1

[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2
