title = "We help entrepreneurs grow their business."
baseURL = "www.example.com"
languageCode = "en-us"
themesDir = "../.."
theme = "hugo-serif-theme"

[params]
google_analytics_id = ""
google_tag_manager_id = ""

  [params.logo]
  standard = "images/spearfish-logo2.png"
  mobile = "images/logo-mobile.svg"
  alt = "Spearfish"

  [params.homepage_meta_tags]
  meta_description = "Fast funding for small business. Same day or 24-72 hour turnaround possible. Good credit, bad credit, no credit."
  meta_og_title = "Spearfish: Fast funding for small business"
  meta_og_type = "website"
  meta_og_url = "https://hugo-serif.netlify.com"
  meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
  meta_og_description = "Spearish makes it easy for small business owners to get the funding they need -- fast."
  meta_twitter_card = "summary"
  meta_twitter_site = "@zerostaticio"
  meta_twitter_creator = "@zerostaticio"

[[menu.main]]
name = "Services"
url = "/services/"
weight = 1

[[menu.main]]
name = "Team"
url = "/team/"
weight = 2

[[menu.footer]]
name = "Home"
url = "/"
weight = 1

[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2
